spring.application.name=climalert-app

server.port=8088

spring.datasource.url=jdbc:h2:file:./data/climalert-db;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

climalert.weather.api-key=${WEATHER_API_KEY:}
climalert.weather.base-url=https://api.weatherapi.com/v1
climalert.weather.location=Buenos Aires, Argentina

climalert.alert.max-temperature-celsius=35
climalert.alert.max-humidity-percentage=60

climalert.mail.recipients[0]=admin@clima.com
climalert.mail.recipients[1]=emergencias@clima.com
climalert.mail.recipients[2]=meteorologia@clima.com

climalert.scheduler.fetch-delay-ms=300000
climalert.scheduler.analysis-delay-ms=60000

logging.level.climate=INFO
logging.level.service=INFO
logging.level.scheduler=INFO
